name: pygeartrain
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy >= 1.9
  - matplotlib
  - sympy
  - pytest
  - shapely
  - imageio
  - pip:
#    - git+https://github.com/eelcohoogendoorn/numga.git
    - git+https://github.com/eelcohoogendoorn/pycomplex.git
